### PR TITLE
docs: remote deployment and socket proxy

### LINKED ISSUE #12: docs: example using configs, secrets and docket socket proxy
Hi there, I hope I'm not becoming your nightmare 😅 

This is what I've come up with to make the swarm-cd deployment a little more secure.

- It uses Tecnativa's docker-socket-proxy to only expose the needed Docker Engine API endpoints; the `DOCKER_HOST` environment variable points to the proxy
- It uses a secret for the `repos.yaml` file, since it can contain auth credentials
- It uses a config for the `stacks.yaml` file, so that it is not bound to a local path, and the stack can be deployed to a remote docker host.

Let me know if you want me to create a PR to add the documentation, and if so, where to put it.

```yaml
---
version: '3.7'
services:
  socket_proxy:
    image: tecnativa/docker-socket-proxy:0.2.0
    deploy:
      placement:
        constraints:
          - node.role == manager
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      TZ: Europe/Rome
      INFO: 1
      SERVICES: 1
      NETWORKS: 1
      SECRETS: 1
      CONFIGS: 1
      POST: 1

  swarm-cd:
    image: ghcr.io/m-adawi/swarm-cd:1.1.0
    depends_on:
      - socket_proxy
    configs:
      - source: stacks
        target: /app/stacks.yaml
        mode: 0400
    environment:
      DOCKER_HOST: tcp://socket_proxy:2375
    secrets:
      - source: repos
        target: /app/repos.yaml
        mode: 0400

configs:
  stacks:
    file: ./stacks.yaml
    name: stacks-${STACKS_MD5}

secrets:
  repos:
    file: ./repos.yaml
    name: repos-${REPOS_MD5}
```

Regarging the environment variables, as I mentioned in https://github.com/m-adawi/swarm-cd/issues/6#issuecomment-2233667970, my command to create and update the swarm-cd stack uses `yq`, `awk` and `md5sum` to handle the config and secret upgrades, and is held in a Taskfile so I just have to `task bootstrap`

```yaml
version: '3'

vars:
  STACK_NAME: swarm-cd
  COMPOSE_FILE: '{{.STACK_NAME}}/docker-compose.yaml'

tasks:
  bootstrap:
    cmds:
      - "eval $(yq '.secrets + .configs | map((key | upcase | sub(\"[^A-Z0-9_]\", \"_\") + \"_MD5\"): .file) | flatten | .[]' swarm-cd/docker-compose.yaml | awk -F ': ' '{ cmd=\"md5sum {{.STACK_NAME}}/\" $2 \"| cut -f1 -d \\\" \\\"\"; while(cmd | getline line) {print $1 \"=\" line}}' | tr '\n' ' ') docker stack deploy -c {{.COMPOSE_FILE}} -d=true {{.STACK_NAME}}"

  cleanup:
    cmds:
      - docker stack rm {{.STACK_NAME}}
```

### PR DESCRIPTION
**Pull request by sanzoghenzo**
this closes #12

### CODE REVIEW

**Comment by m-adawi** [comment]
I want this to be more on how you can set `DOCKER_HOST` to connect to a remote docker socket than how to secure it. If possible, can you please remove the first section about ssh and modify the second section's title to something like: "Connect SwarmCD to a remote docker socket" and then you can use the proxy tool that secures connections as an example.

**Comment by sanzoghenzo** [comment]
I don't really understand your request... To connect SwarmCD to a remote docker, you would need to add the SSH configuration to connect to it (You wouldn't want to use the tcp:// connection to a remote host!);
If you mean a remote docker socket inside the swarm, I don't see any other reason to do it other than to secure it.

**Comment by m-adawi** [comment]
> To connect SwarmCD to a remote docker, you would need to add the SSH configuration to connect to it (You wouldn't want to use the tcp:// connection to a remote host!)

Remote docker doesn't necessarily mean over the internet, it could be just over a private network https://docs.docker.com/config/daemon/remote-access/

> If you mean a remote docker socket inside the swarm, I don't see any other reason to do it other than to secure it.

What I want to say is that I don't want to claim in the README that using docker-socket-proxy is the way to secure docker socket. Because the same way users might have concerns about mounting their socket to SwarmCD they might as well have concerns about mounting it to docker-socket-proxy. 

Sorry if this was a misunderstanding from my part but when you asked if I want to you open the PR in #12 I only meant that I wanna update the docs to state that you can use `DOCKER_HOST` to connect to a remote socket, with docker-socket-proxy as an example.

**Comment by sanzoghenzo** [comment]
Sorry for the delay, I've updated the doc as you instructed.

**Comment by m-adawi** [comment]
Thanks man!

**Pull request merged**
